name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v1.4.2
        with:
             # Yarn command
         cmd: install
      
      - name: Creating build 
        run: yarn build
      - name: installing Surge
        run: npm install -g surge
      - name: deploying on surge
        run: surge ./build https://dummy_app.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
